//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 07:57:54 PM CET 
//


package org.dmike.jaxb.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MenuType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MenuType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://org.dmike.com/hello}EntryType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="item" type="{http://org.dmike.com/hello}ItemType"/&gt;
 *         &lt;element name="checkbox" type="{http://org.dmike.com/hello}CheckBoxType"/&gt;
 *         &lt;element name="menu" type="{http://org.dmike.com/hello}MenuType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MenuType", propOrder = {
    "itemOrCheckboxOrMenu"
})
public class MenuType
    extends EntryType
{

    @XmlElements({
        @XmlElement(name = "item", type = ItemType.class),
        @XmlElement(name = "checkbox", type = CheckBoxType.class),
        @XmlElement(name = "menu", type = MenuType.class)
    })
    protected List<EntryType> itemOrCheckboxOrMenu;

    /**
     * Gets the value of the itemOrCheckboxOrMenu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOrCheckboxOrMenu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOrCheckboxOrMenu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * {@link CheckBoxType }
     * {@link MenuType }
     * 
     * 
     */
    public List<EntryType> getItemOrCheckboxOrMenu() {
        if (itemOrCheckboxOrMenu == null) {
            itemOrCheckboxOrMenu = new ArrayList<EntryType>();
        }
        return this.itemOrCheckboxOrMenu;
    }

}
