//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 07:57:54 PM CET 
//


package org.dmike.jaxb.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dmike.jaxb.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Greetings_QNAME = new QName("http://org.dmike.com/hello", "greetings");
    private final static QName _Punctuation_QNAME = new QName("http://org.dmike.com/hello", "punctuation");
    private final static QName _Exclamation_QNAME = new QName("http://org.dmike.com/hello", "exclamation");
    private final static QName _Quatationmark_QNAME = new QName("http://org.dmike.com/hello", "quatationmark");
    private final static QName _MixTypeNumber_QNAME = new QName("", "number");
    private final static QName _MixTypeCount_QNAME = new QName("", "count");
    private final static QName _MixTypeText_QNAME = new QName("", "text");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dmike.jaxb.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GreetingTypeList }
     * 
     */
    public GreetingTypeList createGreetingTypeList() {
        return new GreetingTypeList();
    }

    /**
     * Create an instance of {@link GreetingType }
     * 
     */
    public GreetingType createGreetingType() {
        return new GreetingType();
    }

    /**
     * Create an instance of {@link NumericZooType }
     * 
     */
    public NumericZooType createNumericZooType() {
        return new NumericZooType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link MixType }
     * 
     */
    public MixType createMixType() {
        return new MixType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link CheckBoxType }
     * 
     */
    public CheckBoxType createCheckBoxType() {
        return new CheckBoxType();
    }

    /**
     * Create an instance of {@link MenuType }
     * 
     */
    public MenuType createMenuType() {
        return new MenuType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GreetingTypeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.dmike.com/hello", name = "greetings")
    public JAXBElement<GreetingTypeList> createGreetings(GreetingTypeList value) {
        return new JAXBElement<GreetingTypeList>(_Greetings_QNAME, GreetingTypeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.dmike.com/hello", name = "punctuation")
    public JAXBElement<String> createPunctuation(String value) {
        return new JAXBElement<String>(_Punctuation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.dmike.com/hello", name = "exclamation", substitutionHeadNamespace = "http://org.dmike.com/hello", substitutionHeadName = "punctuation")
    public JAXBElement<String> createExclamation(String value) {
        return new JAXBElement<String>(_Exclamation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.dmike.com/hello", name = "quatationmark", substitutionHeadNamespace = "http://org.dmike.com/hello", substitutionHeadName = "punctuation")
    public JAXBElement<String> createQuatationmark(String value) {
        return new JAXBElement<String>(_Quatationmark_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number", scope = MixType.class)
    public JAXBElement<Integer> createMixTypeNumber(Integer value) {
        return new JAXBElement<Integer>(_MixTypeNumber_QNAME, Integer.class, MixType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "count", scope = MixType.class)
    public JAXBElement<Integer> createMixTypeCount(Integer value) {
        return new JAXBElement<Integer>(_MixTypeCount_QNAME, Integer.class, MixType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text", scope = MixType.class)
    public JAXBElement<String> createMixTypeText(String value) {
        return new JAXBElement<String>(_MixTypeText_QNAME, String.class, MixType.class, value);
    }

}
