//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 12:20:00 PM CET 
//


package org.dmike.jaxb.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dmike.jaxb.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Greetings_QNAME = new QName("http://org.dmike.com/hello", "greetings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dmike.jaxb.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GreetingTypeList }
     * 
     */
    public GreetingTypeList createGreetingTypeList() {
        return new GreetingTypeList();
    }

    /**
     * Create an instance of {@link GreetingType }
     * 
     */
    public GreetingType createGreetingType() {
        return new GreetingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GreetingTypeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.dmike.com/hello", name = "greetings")
    public JAXBElement<GreetingTypeList> createGreetings(GreetingTypeList value) {
        return new JAXBElement<GreetingTypeList>(_Greetings_QNAME, GreetingTypeList.class, null, value);
    }

}
