
package org.dmike.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSEIImplService", targetNamespace = "http://example.dmike.org/", wsdlLocation = "http://localhost:8080//webserver/HelloSEIImplService?wsdl")
public class HelloSEIImplService
    extends Service
{

    private final static URL HELLOSEIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSEIIMPLSERVICE_EXCEPTION;
    private final static QName HELLOSEIIMPLSERVICE_QNAME = new QName("http://example.dmike.org/", "HelloSEIImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webserver/HelloSEIImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSEIIMPLSERVICE_WSDL_LOCATION = url;
        HELLOSEIIMPLSERVICE_EXCEPTION = e;
    }

    public HelloSEIImplService() {
        super(__getWsdlLocation(), HELLOSEIIMPLSERVICE_QNAME);
    }

    public HelloSEIImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSEIIMPLSERVICE_QNAME, features);
    }

    public HelloSEIImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSEIIMPLSERVICE_QNAME);
    }

    public HelloSEIImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSEIIMPLSERVICE_QNAME, features);
    }

    public HelloSEIImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSEIImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloSEI
     */
    @WebEndpoint(name = "HelloSEIImplPort")
    public HelloSEI getHelloSEIImplPort() {
        return super.getPort(new QName("http://example.dmike.org/", "HelloSEIImplPort"), HelloSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloSEI
     */
    @WebEndpoint(name = "HelloSEIImplPort")
    public HelloSEI getHelloSEIImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.dmike.org/", "HelloSEIImplPort"), HelloSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSEIIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOSEIIMPLSERVICE_EXCEPTION;
        }
        return HELLOSEIIMPLSERVICE_WSDL_LOCATION;
    }

}
