/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dmike16_javaprogramming_celestialBody */

#ifndef _Included_dmike16_javaprogramming_celestialBody
#define _Included_dmike16_javaprogramming_celestialBody
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dmike16_javaprogramming_celestialBody
 * Method:    helloBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dmike16_javaprogramming_celestialBody_helloBody
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
