REM =====================
REM Articoli + Vendite
REM =====================

DROP TABLE Vendite_due;
DROP TABLE Articoli_Due;

CREATE TABLE Articoli_Due(
	CODICE			VARCHAR2(8),
	DESCRIZIONE		VARCHAR2(20),
	GIACENZA		NUMBER(3) DEFAULT 0,
	PREZZO			NUMBER(5) DEFAULT 0,
	CONSTRAINT codice_unico PRIMARY KEY(CODICE)
);

CREATE TABLE Vendite_Due(
	CODICE 			VARCHAR2(8),
	NRICEVUTA		VARCHAR2(5),
	QTAVEN			NUMBER(3),
	CONSTRAINT num_ric PRIMARY KEY(NRICEVUTA,CODICE),
	CONSTRAINT codice_ric FOREIGN KEY(CODICE) REFERENCES Articoli_Due
);
